std_msgs/Header header
std_msgs/String subject
std_msgs/String predicate
std_msgs/String object
std_msgs/Time expiration
std_msgs/Int32 priority
---
std_msgs/Header header
actionlib_msgs/GoalStatus status
std_msgs/String explanation
---
std_msgs/Header header
actionlib_msgs/GoalStatus status
std_msgs/String explanation
