std_msgs/Header header
geometry_msgs/TwistWithCovariance target_twist
std_msgs/Time expiration
std_msgs/Int32 priority
---
geometry_msgs/TwistWithCovarianceStamped final_twist
---
geometry_msgs/TwistWithCovarianceStamped feedback_twist
