std_msgs/Header header
geometry_msgs/PoseWithCovariance target_pose
std_msgs/Time expiration
std_msgs/Int32 priority
---
geometry_msgs/PoseStamped final_pose
---
geometry_msgs/PoseStamped feedback_pose
